apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
     matchLabels:
        {{- range $key, $val := .Values.deploymentlabels }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}	   
  template:
    metadata:
      name: {{ .Values.Name }}
      labels:
        {{- range $key, $val := .Values.deploymentlabels }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.Name }}
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.ports.containerport }}
