apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Name }}-svc
spec:
  type: {{ .Values.servicetype }}
  selector:
     {{- range $key, $val := .Values.deploymentlabels }}
     {{ $key }}: {{ $val | quote }}
     {{- end }}
  ports:
   - protocol: TCP
     port: {{ .Values.ports.serviceport }}
